### ISSUE TITLE
sg_ad_main.ipynb

### ISSUE THREAD

**Issue by dongdongzhaoUP** [ege-erdogan/splitguard#3]
An interesting work! Could you please provide the file and the code to generate and save Gradients, which are used in sg_ad_main.ipynb.
Thanks a lot!

**Comment by ege-erdogan** [comment]
Hi @dongdongzhaoUP, we used a slightly modified version of https://github.com/zlijingtao/SplitNN_FSHA_torch as the PyTorch FSHA implementation. 

The modifications contain some other components besides gradient-collecting but this gist should be enough to replace with the file of the same name in the original code: https://gist.github.com/ege-erdogan/38c5b2dbce86eb0e391848e4997702b7 (more specifically around lines 39 and 195)

The collected gradients are then stored as fields of the `FSHA` object so can be accessed easily from a Jupyter notebook. 

Hope this helps! Let us know if you have further questions.
