### ISSUE TITLE
how to generate files

### ISSUE THREAD

**Issue by speedand** [ege-erdogan/splitguard#4]
Hello, I want to know how to generate the files in these two directories.
cifar10_HONEST/honest_cifar_grads_
cifar10_newAtt_fake/FSHA_newAtt_cifar10_fakes_

**Comment by robuno** [comment]
Hello @speedand, we used a slightly modified version of the source code of the [FSHA PyTorch implementation](https://github.com/zlijingtao/SplitNN_FSHA_torch). To get information about the changes made and modifications about your question, you can check the [closed issue here](https://github.com/ege-erdogan/splitguard/issues/3). You can access the gradients in the `FSHA` object and save them in the Notebook as you wish.

I hope this answer and links help. Feel free to let me know if you have any related questions.
